server:
  port: 9000

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.148.138:30306/auth_control?useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
#  application:
#    name:
#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true
# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

auth:
  code: auth-centre
  auth-field: auth_keys